# Site settings
title: "长风"
description: "#"
podcast-description: "吾生也有涯，而知也无涯，以有涯随无涯，殆已。"
url:  # Actual base url of the website
baseurl: #"/"   # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Erick"
  email: "erichueng@gmail.com"
  url: "https://github.com/cppfish"
permalink: pretty
permalink: /:year/:month/:day/:title
keywords: [computer science, jekyll, program]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 3
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
# twitter:
#   username: #
#   card: #
# facebook: 
#   app_id: # 
logo: /assets/img/Podcast_Cover.png
social:
  name: Erick
  links:
    - https://github.com/cppfish
    - https://www.linkedin.com/in/erichueng
lang: zh-CN

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Erick
podcast_author: Erick Chueng
podcast_email: erichueng@gmail.com
# podcast_subtitle: "A Jekyll Theme designed for Podcasters"
# podcast_summary: "A Jekyll Theme designed for Podcasters. This is your podcast's summary."
# podcast_description: "A Jekyll Theme designed for Podcasters. This is your podcast's description."
# podcast_explicit: "no"
# podcast_type: serial 
# podcast_lang: en
# podcast_launch: "2019-07-20" #Launch date of your podcast
# podcast_copyright: "&#xA9;Alessio Franceschi"
# podcast_feed: 
# podcast_artwork: "/assets/img/Podcast_Cover.png"