# Almost all the things in the website can be customized from here.
# Changing title and description according to your website requirement is important.

# Footer stuff here....TODO   get this to replicate elsewhere
title: Precious Stone
title-min: #
title-creds: 这个沙漠的后面是什么地方？ 是另外一个沙漠。  
#title.creds: "OTR, DRS, CDI, CPT"
description: info
email: erichueng@gmail.com # The contact form submission will be done to this email address.
phone: #
# url: 
default-image: /images/avocado-cover.png # This image will be shown on sharing any page on social media. For example: Homepage, about page etc. This image should be bigger than 200x200px. This image is not used for posts. Posts use their own image mentioned in individual posts.
header: /images/banner.jpg
# Author details shows up at the end of every article/blog
author:
    name: Luke
    bio: "我梦见我家乡的桃花开了。  <br/><br/>原来我已经有很多年没回去了。"
    image: author-image.png # Choose a 200x200px image and place it inside /images directory.
    #facebook: https://www.facebook.com/missybell.atx
    #twitter: https://twitter.com
    #quora: https://www.quora.com/
    linkedin: https://www.linkedin.com/in/erichueng/

# Kramdown is supported by Github
markdown: kramdown

# Mathjax setting
enable-mathjax: yes

# Charts
enable-chartjs: yes


# This defines how the URLs should look like
permalink: /blog/:title/

# Pagination - Posts per page in the blog index
paginate: 6
paginate_path: /blog/page:num/

# Define titles for the sections
name: Luke Blog
projects: All things OTR, DRS, CDI, and CPT


# Jekyll will read contents inside _pages only if we tell it to
include:
    - _pages

# Google Ananlytics Tracker
analytics: # UA-92266803-2  # Sign up with Google analytics and replce with your analytics ID

#Tawk.to integration
#tawkto-id: 5cb170e9c1fe2560f3fea30c # Sign up with tawk.to and go to Admin >> Property settings and replace the Site ID here
tawkto-id: # 5cdf2b222846b90c57af1bed # This is our new tawk.to id  

# Share buttons
share: yes # Change it to `no` to remove share buttons.


# Comments by Disqus # Sign up with Disqus to get your shortcode. Leave it blank if you do not want to run diqus code on the website.
disqus: # missybell-atx #webjeda-demo


#
#   ,-----.                                                    ,--.
#  '  .--./ ,---. ,--,--,--. ,---. ,--.--. ,---.  ,---.  ,---. `--' ,---. ,--,--,
#  |  |    | .-. ||        || .-. ||  .--'| .-. :(  .-' (  .-' ,--.| .-. ||      \
#  '  '--'\' '-' '|  |  |  || '-' '|  |   \   --..-'  `).-'  `)|  |' '-' '|  ||  |
#   `-----' `---' `--`--`--'|  |-' `--'    `----'`----' `----' `--' `---' `--''--'
#                           `--'
# All compression variables are declared here.

sass:
 style: compressed

#compress.html
compress_html:
  clippings: [html, head, meta, title, link, body, div, script, header, footer]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

####################################################################################################

# destination: _avocado

exclude:
    - .git


# These plugins are supported by github by default and can be installed locally using ruby gems
plugins:
    - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
    - jekyll-feed       # Adds feed to the website at /feed.xml
    - jekyll-paginate   # Used for sorting posts by page numbers.
    - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
