---
title: Hat Text
# url: 
# baseurl: 
desc: A minimal blog for off-topic blog entries.
about: I am a web developer, currently living in Shenzhen.
image: /img/undock_pressed.svg
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugins:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
# - CNAME

paginate: 5
# paginate_path: "/:num/"
paginate_path: "/page:num/"

highlighter: rouge
# permalink: pretty
permalink: /blog/:title/